apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog-container
        image: s223021831/book-catalog:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://root:QO582QvXuApJAw1J0HGdAIkguDWYykKW@dpg-cr7u8n5svqrc73dl6ggg-a.oregon-postgres.render.com/book_kh1m"
        - name: APP_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
